#!/usr/bin/env python3
"""
clean-bo-spyod-jug-srung-grel.py
Generated by the clean-commentary-text skill (predecessor of clean-raw-text).

HISTORICAL EXAMPLE — DOES NOT RUN IN THIS REPO. This is a preserved worked
example of a generated cleaning script, kept for reference (see
../SKILL.md Step 3 and ./README.md). The SOURCE/OUTPUT paths below point into
the original bodhisattvacharyavatara-rails vault (1-SOURCES/, 0-INBOX/),
which does not exist in this repo. Do not run this file as-is.

Removes mechanical OCR/PDF debris from (original vault path):
  1-SOURCES/Commentaries/bo-སྤྱོད་འཇུག་སྒྲུང་འགྲེལ།.md

Output (original vault path):
  0-INBOX/bo-spyod-jug-srung-grel-clean.md

Issues found during inspection (Step 1 profile):
  - Page markers: lines matching ^\\s*-\\d+-\\s*$ (every ~15 lines throughout)
  - Running header A (single-line): "མཁྱེན་བརྩེའི་འོད་སྣང་ལས། སྤྱོད་འཇུག་སྒྲུང་འགྲེལ།"
  - Running header B (split across two lines):
      "མཁྱེན་བརྩེའི་འོད་སྣང་ལས།"  followed immediately by  "སྤྱོད་འཇུག་སྒྲུང་འགྲེལ།"
  - Running footer A: "སྤྱོད་འཇུག་སྒྲུང་འགྲེལ་ལས་འབྲས་གསལ་བའི་མེ་ལོང་ཞེས་བྱ་བ་བཞུགས།"
  - Non-breaking tshegs (U+0F0C ༌) replacing standard tshegs (U+0F0B ་)
  - Extra spaces inserted mid-word by PDF justification (e.g. "སངས་རྒྱས་ དང་ བྱང་ཆུབ་")
  - Orphaned short lines (mid-sentence OCR line fragments, e.g. "རེ།" alone on a line)
"""

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths — HISTORICAL, point into the original vault, not this repo. See the
# module docstring above; do not run this file as-is.
# ---------------------------------------------------------------------------
VAULT = Path(__file__).resolve().parents[3]   # original vault root
SOURCE = VAULT / "1-SOURCES/Commentaries/bo-སྤྱོད་འཇུག་སྒྲུང་འགྲེལ།.md"
OUTPUT = VAULT / "0-INBOX/bo-spyod-jug-srung-grel-clean.md"

# ---------------------------------------------------------------------------
# Lines to remove verbatim (stripped content must match exactly)
# ---------------------------------------------------------------------------
REMOVE_LINES: set[str] = {
    # Running header A (single line)
    "མཁྱེན་བརྩེའི་འོད་སྣང་ལས། སྤྱོད་འཇུག་སྒྲུང་འགྲེལ།",
    # Running header B part 1 (when split across two lines)
    "མཁྱེན་བརྩེའི་འོད་སྣང་ལས།",
    # Running footer
    "སྤྱོད་འཇུག་སྒྲུང་འགྲེལ་ལས་འབྲས་གསལ་བའི་མེ་ལོང་ཞེས་བྱ་བ་བཞུགས།",
}

# When header B is split, part 2 appears on the very next line.
# We handle it as a separate entry so it is caught individually even
# if the two-line pattern breaks mid-file.
REMOVE_LINES.add("སྤྱོད་འཇུག་སྒྲུང་འགྲེལ།")

# ---------------------------------------------------------------------------
# Patterns
# ---------------------------------------------------------------------------
PAGE_MARKER  = re.compile(r'^\s*-\d+-\s*$')
MID_SPACE    = re.compile(r'([ༀ-࿿]) +([ༀ-࿿])')
NBT          = '༌'   # ༌  non-breaking tsheg
STD_TSHEG    = '་'   # ་  standard inter-syllable tsheg

# Sentence / verse endings after which we do NOT join the next line
SENTENCE_END = re.compile(r'[།॥།༎]\s*$')

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def is_verse_line(line: str) -> bool:
    """Verse lines end with ། །  or །།  (shad pairs)."""
    s = line.rstrip()
    return s.endswith('། །') or s.endswith('།།') or s.endswith('། །།')


def remove_mid_spaces(line: str) -> tuple[str, int]:
    """Collapse spaces between Tibetan Unicode characters. Returns (new_line, n_removals)."""
    total = 0
    prev = None
    while prev != line:
        prev = line
        line, n = MID_SPACE.subn(r'\1\2', line)
        total += n
    return line, total


# ---------------------------------------------------------------------------
# Main clean function
# ---------------------------------------------------------------------------

def clean(text: str) -> tuple[str, dict]:
    lines = text.split('\n')
    out: list[str] = []
    stats = {
        'page_markers_removed': 0,
        'header_footer_lines_removed': 0,
        'nbt_replacements': 0,
        'mid_word_spaces_removed': 0,
        'lines_joined': 0,
    }

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # 1. Page markers
        if PAGE_MARKER.match(line):
            stats['page_markers_removed'] += 1
            i += 1
            continue

        # 2. Running headers / footers
        if stripped in REMOVE_LINES:
            stats['header_footer_lines_removed'] += 1
            i += 1
            continue

        # 3. Non-breaking tshegs → standard tshegs
        if NBT in line:
            n = line.count(NBT)
            line = line.replace(NBT, STD_TSHEG)
            stats['nbt_replacements'] += n

        # 4. Mid-word spaces (skip verse lines to preserve spacing)
        if not is_verse_line(line):
            line, n = remove_mid_spaces(line)
            stats['mid_word_spaces_removed'] += n

        # 5. Join orphaned line fragments to the previous line.
        #    Condition: current line is non-empty, the last output line is
        #    non-empty, the last output line does NOT end with sentence-closing
        #    punctuation, AND the current line is short (≤ 20 chars stripped).
        if (out
                and stripped
                and len(stripped) <= 20
                and not SENTENCE_END.search(out[-1])
                and not is_verse_line(out[-1])
                and not PAGE_MARKER.match(line)
                and stripped not in REMOVE_LINES):
            out[-1] = out[-1].rstrip() + ' ' + stripped
            stats['lines_joined'] += 1
            i += 1
            continue

        out.append(line)
        i += 1

    # 6. Normalise runs of more than one blank line → single blank line
    result = re.sub(r'\n{3,}', '\n\n', '\n'.join(out))

    return result, stats


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    if not SOURCE.exists():
        print(f"ERROR: source file not found:\n  {SOURCE}", file=sys.stderr)
        sys.exit(1)

    print(f"Reading: {SOURCE}")
    text = SOURCE.read_text(encoding='utf-8')
    print(f"  {len(text):,} characters, {text.count(chr(10)):,} lines")

    cleaned, stats = clean(text)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')

    print("\n=== Cleaning summary ===")
    for k, v in stats.items():
        print(f"  {k.replace('_', ' ')}: {v:,}")
    print(f"\nOutput written to: {OUTPUT}")
    print("\nNext step: run format-commentary on the cleaned draft.")


if __name__ == '__main__':
    main()
