#!/usr/bin/env python3
"""
generate_termbase.py
====================
Reads one or more markdown translation files, computes TF-IDF against the
Reuters-21578 general-English IDF corpus (idf_corpus.py), and writes:

  • A ranked termbase report for each individual translation.
  • When two or more inputs are given, a side-by-side comparison report
    showing shared vocabulary, per-translation signatures, and a full
    cross-translation table.

Usage
-----
    # single file (default: Rhys Davids)
    python3 generate_termbase.py

    # explicit single input
    python3 generate_termbase.py --input 1-SOURCES/Translations/en-1-rhys_davids.md

    # multiple inputs → individual reports + comparison
    python3 generate_termbase.py \\
        --input 1-SOURCES/Translations/en-1-rhys_davids.md \\
                1-SOURCES/Translations/en-2-another.md

    # custom output directory (all reports land here)
    python3 generate_termbase.py --input a.md b.md --outdir scripts/output/run1
"""

import re
import sys
import json
import argparse
import pathlib
from datetime import date

# idf_corpus.py lives in the output/ subfolder next to this script.
sys.path.insert(0, str(pathlib.Path(__file__).parent / "output"))
from idf_corpus import IDF_CORPUS

# ---------------------------------------------------------------------------
# Paths (defaults — overridden by CLI args in main())
# ---------------------------------------------------------------------------
HERE      = pathlib.Path(__file__).parent            # pali-english/english_keyword/
REPO_ROOT = HERE.parent.parent                       # abhidhamma-rails/
_DEFAULT_INPUT  = REPO_ROOT / "1-SOURCES/Translations/en-1-rhys_davids.md"
_DEFAULT_OUTDIR = HERE / "output"

# ---------------------------------------------------------------------------
# IDF table  — Reuters-21578 corpus (10,788 newswire documents)
#
# Sourced from idf_corpus.py (generated by generate_idf_corpus.py).
# Formula: idf(t) = log((1 + N) / (1 + df(t))) + 1  [sklearn smooth IDF]
#
# Approximate scoring bands in this corpus:
#   1.0  – 1.5   function / grammatical words   (present in nearly every document)
#   1.5  – 3.0   common content words
#   3.0  – 6.0   moderately rare / domain words
#   6.0  – 9.0   uncommon / specialist English
#   9.0  – 9.6   near-hapax in Reuters (max ≈ log(10789/2)+1 ≈ 9.59)
#
# Words absent from the corpus (Pāli transliterations, Victorian coinages)
# receive IDF_UNKNOWN — set to the corpus maximum to mark them as maximally
# rare from a general-English perspective.
# ---------------------------------------------------------------------------
IDF: dict[str, float] = IDF_CORPUS

# Fallback for words absent from the Reuters vocabulary.
IDF_UNKNOWN: float = 9.59

# ---------------------------------------------------------------------------
# Stop-words (excluded from counting — grammatical skeleton only)
# ---------------------------------------------------------------------------
STOPWORDS = {
    "the","a","an","and","or","of","in","on","to","at","by","for","with",
    "that","this","these","those","is","are","was","were","be","been","being",
    "have","has","had","do","does","did","will","would","shall","should",
    "may","might","can","could","not","no","nor","so","yet","but","both",
    "either","neither","as","if","then","there","here","when","where","which",
    "who","whom","whose","what","how","it","its","he","she","they","we","you",
    "i","me","him","her","them","us","my","your","his","our","their",
    "from","into","up","out","about","after","before","between","through",
    "now","also","only","just","even","than","more","very","each","all","any",
    "some","such","other","same","own","new","first","last","long","great",
    "little","good","well","back","over","still","though","however","thus",
    "upon","per","own","one","two","three","four","five","six","seven","eight",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def strip_frontmatter(text: str) -> str:
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:]
    return text


def tokenize(text: str) -> list[str]:
    text = strip_frontmatter(text)
    # drop Obsidian transclusion lines (e.g. "![[1-SOURCES/Translations/bo-...]]")
    # — their file-path fragments would otherwise pollute the word counts.
    text = re.sub(r"^!\[\[.*$", " ", text, flags=re.MULTILINE)
    text = re.sub(r"\^[\w\-]+", " ", text)           # verse markers
    text = re.sub(r"[#\[\]`*_>|§]", " ", text)       # markdown syntax
    text = re.sub(r"\d+", " ", text)                  # numbers
    # keep hyphened compounds as single tokens (e.g. self-collectedness)
    tokens = re.findall(
        r"[a-zA-ZāīūṭḍṅñṇḷṃṁĀĪŪṬḌṄÑṆḶṂṀ]+"
        r"(?:[-][a-zA-ZāīūṭḍṅñṇḷṃṁĀĪŪṬḌṄÑṆḶṂṀ]+)*",
        text,
    )
    return [t.lower() for t in tokens]


def count_tf(path: pathlib.Path) -> dict[str, int]:
    raw    = tokenize(path.read_text(encoding="utf-8"))
    counts: dict[str, int] = {}
    for w in raw:
        if w not in STOPWORDS and len(w) > 2:
            counts[w] = counts.get(w, 0) + 1
    return counts


def tfidf(word: str, count: int, total: int) -> float:
    tf  = count / total
    idf = IDF.get(word, IDF_UNKNOWN)
    return round(tf * idf * 1_000_000, 4)


# ---------------------------------------------------------------------------
# Build rows sorted by TF-IDF descending
# ---------------------------------------------------------------------------

def build_rows(tf: dict[str, int]) -> list[dict]:
    total = sum(tf.values())
    rows  = []
    for word, count in tf.items():
        score = tfidf(word, count, total)
        rows.append({"word": word, "count": count, "score": score,
                     "idf": IDF.get(word, IDF_UNKNOWN)})
    rows.sort(key=lambda r: r["score"], reverse=True)
    return rows


# ---------------------------------------------------------------------------
# Determine TF-IDF band label
# ---------------------------------------------------------------------------
_BANDS = [
    (50_000, "🔴 extremely high — text-exclusive"),
    (10_000, "🟠 very high — domain-specific"),
    ( 3_000, "🟡 high — specialist register"),
    (   500, "🟢 medium — moderately distinctive"),
    (    50, "🔵 low — common in general English"),
    (     0, "⚪ very low — function / universal word"),
]

def band(score: float) -> str:
    for threshold, label in _BANDS:
        if score >= threshold:
            return label
    return "⚪ very low"


# ---------------------------------------------------------------------------
# English-only filter
# Pāli transliterations use diacritical characters not found in English.
# Any token containing one of these is excluded from JSON output.
# ---------------------------------------------------------------------------
_PALI_CHARS = re.compile(r"[āīūṭḍṅñṇḷṃṁĀĪŪṬḌṄÑṆḶṂṀ]")

def is_english(word: str) -> bool:
    """Return True if the word contains no Pāli diacritical characters."""
    return not bool(_PALI_CHARS.search(word))


# ---------------------------------------------------------------------------
# Combined JSON output
# ---------------------------------------------------------------------------

def write_combined_json(
    comp: dict,          # stem → {"rows": [...], "row_map": {...}, "total": int}
    sources: list[pathlib.Path],
    dest: pathlib.Path,
) -> None:
    """
    Write a single JSON file with all unique English words across all translations.
    Each entry is just {"word": "..."}, sorted by avg TF-IDF descending.
    Pāli words (diacritical characters) are excluded.
    """
    stems     = [src.stem for src in sources]
    all_words = set()
    for d in comp.values():
        all_words.update(d["row_map"].keys())

    # filter to English-only, sort by avg TF-IDF descending
    english_words = [w for w in all_words if is_english(w)]
    english_words.sort(
        key=lambda w: sum(comp[s]["row_map"].get(w, {}).get("score", 0.0) for s in stems) / len(stems),
        reverse=True,
    )

    payload = {"word": list(dict.fromkeys(english_words))}  # dict.fromkeys preserves order, drops dupes

    dest.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Written  → {dest}  ({len(payload['word']):,} English terms)")


# ---------------------------------------------------------------------------
# Single-translation Markdown renderer
# ---------------------------------------------------------------------------

def render_md(rows: list[dict], source: pathlib.Path) -> str:
    today   = date.today().isoformat()
    total_w = sum(r["count"] for r in rows)
    n       = len(rows)
    stem    = source.stem

    band_counts: dict[str, int] = {}
    for r in rows:
        b = band(r["score"])
        band_counts[b] = band_counts.get(b, 0) + 1

    top    = rows[:50]
    bottom = rows[-50:]

    L: list[str] = []

    L += [
        "---",
        f"title: TF-IDF Vocabulary Analysis — {stem}",
        f"source: {source}",
        "corpus: Reuters-21578 (10,788 newswire documents) via NLTK · sklearn TfidfVectorizer(smooth_idf=True)",
        "method: TF × IDF — term frequency in translation vs. inverse document frequency in Reuters corpus",
        f"generated: {today}",
        f"unique_terms: {n}",
        f"total_content_tokens: {total_w:,}",
        "status: draft",
        "---",
        "",
    ]

    L += [
        f"# TF-IDF Vocabulary Analysis — {stem}",
        "",
        f"Generated **{today}** · source: `{source.name}` · **{n:,} unique content terms** ranked.",
        "",
        "This report answers two questions:",
        "",
        "1. **Which words in this translation are most frequent here but rare in everyday English?**  ",
        "   → High TF-IDF score. These are the lexical signatures of the text.",
        "2. **Which words appear in the text but are also very common in general English?**  ",
        "   → Low TF-IDF score. These look familiar but carry specialist meaning here.",
        "",
        "---",
        "",
    ]

    L += [
        "## Methodology",
        "",
        "**Term Frequency (TF)** — count of each word in the translation, normalised by total content-token count.",
        "Frontmatter, verse markers (`^1-2`), numbers and markdown syntax are stripped before counting.",
        "",
        "**Inverse Document Frequency (IDF)** — computed from the Reuters-21578 newswire corpus",
        "(10,788 documents, ~1.3 M tokens) using sklearn's smooth IDF formula:",
        "`idf(t) = log((1 + N) / (1 + df(t))) + 1`. Corpus maximum ≈ 9.59. Scale:",
        "",
        "| IDF range | Meaning |",
        "|-----------|---------|",
        "| 1.0 – 1.5 | Function word — present in virtually every document |",
        "| 1.5 – 3.0 | Common content word — high general-English frequency |",
        "| 3.0 – 6.0 | Moderately rare — limited domain or register |",
        "| 6.0 – 9.0 | Uncommon / archaic — rare in Reuters |",
        "| 9.59 (max) | Absent from Reuters — domain-exclusive, coined, or Pāli |",
        "",
        "**TF-IDF score** = TF × IDF × 10⁶ (scaled for readability).",
        "",
        "**Colour bands** used in the table:",
        "",
        "| Band | Score range | Interpretation |",
        "|------|-------------|----------------|",
        "| 🔴 | ≥ 50,000 | Text-exclusive — word essentially does not exist outside this translation |",
        "| 🟠 | 10,000 – 49,999 | Domain-specific — Buddhist / Abhidhamma vocabulary |",
        "| 🟡 | 3,000 – 9,999 | Specialist register — unusual in general English |",
        "| 🟢 | 500 – 2,999 | Moderately distinctive — identifiable domain presence |",
        "| 🔵 | 50 – 499 | Moderately common — has general English presence |",
        "| ⚪ | 0 – 49 | Universal / function word |",
        "",
        "---",
        "",
    ]

    L += [
        "## Distribution by Band",
        "",
        "| Band | Terms | % of vocabulary |",
        "|------|-------|----------------|",
    ]
    for threshold, label in _BANDS:
        c = band_counts.get(label, 0)
        pct = f"{100 * c / n:.1f}" if n else "0.0"
        L.append(f"| {label} | {c:,} | {pct}% |")
    L += ["", "---", ""]

    L += [
        "## Most Distinctive Words (highest TF-IDF)",
        "",
        "Words that appear **frequently in this text** yet are **rare or absent in general English**.",
        "",
    ]
    for i, r in enumerate(top, 1):
        b = band(r["score"])
        L.append(f"**{i}. {r['word']}** — count: {r['count']}, TF-IDF: {r['score']:,.0f}, IDF: {r['idf']} {b}")
    L += ["", "---", ""]

    L += [
        "## Least Distinctive Words (lowest TF-IDF)",
        "",
        "Words that appear in this text but are also extremely common in general English.",
        "",
    ]
    for i, r in enumerate(reversed(bottom), 1):
        b = band(r["score"])
        L.append(f"**{i}. {r['word']}** — count: {r['count']}, TF-IDF: {r['score']:,.2f}, IDF: {r['idf']} {b}")
    L += ["", "---", ""]

    L += [
        "## Full Ranked Table",
        "",
        f"All {n:,} content terms, sorted by TF-IDF descending.",
        "",
        "| Rank | Word | Count | TF-IDF | IDF | Band |",
        "|------|------|-------|--------|-----|------|",
    ]
    for i, r in enumerate(rows, 1):
        b     = band(r["score"])
        score = f"{r['score']:,.2f}"
        L.append(f"| {i} | **{r['word']}** | {r['count']} | {score} | {r['idf']} | {b} |")

    L += [
        "",
        "---",
        "",
        f"*Corpus reference: Reuters-21578 (10,788 newswire documents) via NLTK · "
        f"sklearn TfidfVectorizer(smooth\\_idf=True, lowercase=True).*  ",
        f"*Generated {today} by `generate_termbase.py`.*",
    ]

    return "\n".join(L)


# ---------------------------------------------------------------------------
# Multi-translation comparison
# ---------------------------------------------------------------------------

def build_comparison(sources: list[pathlib.Path]) -> dict:
    """
    Returns::

        {
          stem: {
            "rows":    [sorted row dicts],
            "row_map": {word: row_dict},
            "total":   int,
          },
          ...
        }
    """
    result = {}
    for src in sources:
        tf    = count_tf(src)
        rows  = build_rows(tf)
        result[src.stem] = {
            "rows":    rows,
            "row_map": {r["word"]: r for r in rows},
            "total":   sum(tf.values()),
        }
    return result


def render_comparison_md(
    comp: dict,
    sources: list[pathlib.Path],
) -> str:
    """
    Produce a side-by-side comparison report for two or more translations.

    Sections
    --------
    1. Summary table — unique terms, total tokens, top-5 words per translation
    2. Shared vocabulary — words in ALL translations, ranked by avg TF-IDF
    3. Signature terms — top-25 words per translation absent/much lower elsewhere
    4. Full cross-translation table — all words, one score column per translation
    """
    today  = date.today().isoformat()
    stems  = [src.stem for src in sources]
    n_src  = len(stems)

    # ── universe of all words ────────────────────────────────────────────────
    all_words: set[str] = set()
    for d in comp.values():
        all_words.update(d["row_map"].keys())

    # ── per-word cross-translation data ─────────────────────────────────────
    cross: dict[str, dict[str, float]] = {
        word: {s: comp[s]["row_map"].get(word, {}).get("score", 0.0) for s in stems}
        for word in all_words
    }

    # ── shared words (appear in every translation) ───────────────────────────
    shared_words = [w for w in all_words if all(cross[w][s] > 0 for s in stems)]
    shared_words.sort(
        key=lambda w: sum(cross[w][s] for s in stems) / n_src,
        reverse=True,
    )

    # ── signature words per translation ──────────────────────────────────────
    # A word is a "signature" if its score in this translation is ≥ 3×
    # the score in every other translation (or the word is absent elsewhere).
    def signatures(stem: str, top_n: int = 25) -> list[str]:
        out = []
        for r in comp[stem]["rows"]:
            w, me = r["word"], r["score"]
            if me == 0:
                continue
            others = [cross[w][s] for s in stems if s != stem]
            if all((me >= 3 * o) if o > 0 else True for o in others):
                out.append(w)
                if len(out) >= top_n:
                    break
        return out

    # ── IDF lookup helper ────────────────────────────────────────────────────
    def word_idf(word: str) -> float:
        for d in comp.values():
            if word in d["row_map"]:
                return d["row_map"][word]["idf"]
        return IDF_UNKNOWN

    # ── render ───────────────────────────────────────────────────────────────
    stems_label  = " · ".join(stems)
    score_header = " | ".join(f"TF-IDF ({s})" for s in stems)
    score_sep    = " | ".join("---" for _ in stems)

    L: list[str] = []

    # frontmatter
    L += [
        "---",
        f"title: TF-IDF Comparison — {stems_label}",
        "corpus: Reuters-21578 (10,788 newswire documents) via NLTK · sklearn TfidfVectorizer(smooth_idf=True)",
        "method: TF × IDF — per-translation term frequencies vs. Reuters IDF",
        f"generated: {today}",
        f"translations: {n_src}",
        f"combined_vocabulary: {len(all_words):,}",
        f"shared_vocabulary: {len(shared_words):,}",
        "status: draft",
        "---",
        "",
        f"# TF-IDF Comparison — {n_src} Translations",
        "",
        f"Generated **{today}** · comparing **{n_src} translations** against the Reuters-21578 IDF corpus.",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Translations compared | {n_src} |",
        f"| Combined vocabulary | {len(all_words):,} unique terms |",
        f"| Shared vocabulary | {len(shared_words):,} terms present in all translations |",
        f"| Translation-exclusive terms | {len(all_words) - len(shared_words):,} terms in only one translation |",
        "",
        "---",
        "",
    ]

    # ── 1. Per-translation summary ───────────────────────────────────────────
    L += [
        "## Per-Translation Summary",
        "",
        "| Translation | Unique terms | Total tokens | Top-5 words (TF-IDF) |",
        "|-------------|-------------|--------------|----------------------|",
    ]
    for stem in stems:
        d    = comp[stem]
        top5 = ", ".join(r["word"] for r in d["rows"][:5])
        L.append(f"| `{stem}` | {len(d['rows']):,} | {d['total']:,} | {top5} |")
    L += ["", "---", ""]

    # ── 2. Shared vocabulary top-50 ──────────────────────────────────────────
    L += [
        "## Shared Vocabulary — Top 50",
        "",
        "Words present in every translation, ranked by average TF-IDF.",
        "High **Δ** means the word is lexically dominant in one translation but not others.",
        "",
        f"| Rank | Word | IDF | {score_header} | Avg | Δ |",
        f"|------|------|-----|{score_sep}|-----|---|",
    ]
    for i, word in enumerate(shared_words[:50], 1):
        scores      = [cross[word][s] for s in stems]
        avg         = sum(scores) / n_src
        delta       = max(scores) - min(scores)
        idf_val     = word_idf(word)
        score_cells = " | ".join(f"{sc:,.0f}" for sc in scores)
        L.append(f"| {i} | **{word}** | {idf_val} | {score_cells} | {avg:,.0f} | {delta:,.0f} |")
    L += ["", "---", ""]

    # ── 3. Signature terms per translation ───────────────────────────────────
    L += [
        "## Signature Terms per Translation",
        "",
        "Words where one translation's TF-IDF score is ≥ 3× higher than all others",
        "(or absent elsewhere). These reveal each translator's distinctive vocabulary choices.",
        "",
    ]
    for stem in stems:
        sigs = signatures(stem)
        L += [f"### `{stem}`", ""]
        if sigs:
            for rank, word in enumerate(sigs, 1):
                me         = cross[word][stem]
                others_str = "  ".join(
                    f"`{s}`: {cross[word][s]:,.0f}" for s in stems if s != stem
                )
                L.append(f"**{rank}. {word}** — TF-IDF: {me:,.0f}  ({others_str})")
        else:
            L.append("*No exclusive signature terms found.*")
        L.append("")
    L += ["---", ""]

    # ── 4. Full cross-translation table ──────────────────────────────────────
    all_sorted = sorted(
        all_words,
        key=lambda w: sum(cross[w][s] for s in stems) / n_src,
        reverse=True,
    )

    L += [
        "## Full Cross-Translation Table",
        "",
        f"All {len(all_words):,} terms in at least one translation, sorted by average TF-IDF.",
        "Score = 0 means the word is absent from that translation.",
        "",
        f"| Rank | Word | IDF | {score_header} | Avg | Band (avg) |",
        f"|------|------|-----|{score_sep}|-----|-----------|",
    ]
    for i, word in enumerate(all_sorted, 1):
        scores      = [cross[word][s] for s in stems]
        avg         = sum(scores) / n_src
        idf_val     = word_idf(word)
        b           = band(avg)
        score_cells = " | ".join(f"{sc:,.2f}" for sc in scores)
        L.append(f"| {i} | **{word}** | {idf_val} | {score_cells} | {avg:,.2f} | {b} |")

    L += [
        "",
        "---",
        "",
        f"*Corpus reference: Reuters-21578 (10,788 newswire documents) via NLTK · "
        f"sklearn TfidfVectorizer(smooth\\_idf=True, lowercase=True).*  ",
        f"*Generated {today} by `generate_termbase.py`.*",
    ]

    return "\n".join(L)



# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Compute TF-IDF vocabulary analysis for one or more markdown "
            "translation files. Produces an individual report per file; when "
            "multiple files are given, also produces a side-by-side comparison."
        ),
    )
    p.add_argument(
        "--input", "-i",
        metavar="PATH",
        nargs="+",
        default=None,
        help=(
            "One or more paths to source markdown translation files. "
            f"(default: {_DEFAULT_INPUT})"
        ),
    )
    p.add_argument(
        "--outdir", "-o",
        metavar="DIR",
        default=None,
        help=(
            "Directory for all output reports. "
            f"(default: {_DEFAULT_OUTDIR})"
        ),
    )
    p.add_argument(
        "--bottom", "-b",
        metavar="N",
        type=int,
        default=None,
        help=(
            "Also write a '<stem>_bottom_N.json' report of the N most frequent "
            "keywords sorted by TF-IDF ascending (lowest distinctiveness first). "
            "Useful for identifying stopword candidates."
        ),
    )
    return p.parse_args()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args   = _parse_args()
    outdir = pathlib.Path(args.outdir).resolve() if args.outdir else _DEFAULT_OUTDIR
    outdir.mkdir(parents=True, exist_ok=True)

    sources = (
        [pathlib.Path(p).resolve() for p in args.input]
        if args.input
        else [_DEFAULT_INPUT]
    )

    for src in sources:
        if not src.exists():
            raise FileNotFoundError(f"Translation not found:\n  {src}")

    # ── Build TF-IDF data ────────────────────────────────────────────────────
    comp       = build_comparison(sources)
    stems_slug = "_vs_".join(src.stem for src in sources) if len(sources) > 1 else sources[0].stem

    # ── Combined JSON (all sources, English words only) ──────────────────────
    write_combined_json(comp, sources, outdir / (stems_slug + "_termbase.json"))

    # ── Keyword → verses JSON ─────────────────────────────────────────────────
    kw_data = write_keyword_verses_json(comp, sources, outdir / (stems_slug + "_keyword_verses.json"))

    # ── Bottom-N report (optional) ────────────────────────────────────────────
    if args.bottom:
        write_bottom_json(kw_data, args.bottom, outdir / (stems_slug + f"_bottom_{args.bottom}.json"))

    write_verse_keywords_json(kw_data, outdir / (stems_slug + "_verse_keywords.json"))

# ---------------------------------------------------------------------------
# Verse extraction
# ---------------------------------------------------------------------------

# Matches verse markers like ^1-1, ^2-34, ^I-0, ^0
_VERSE_MARKER = re.compile(r"\^([\w][\w\-]*\d+)\s*$")


def extract_verses(path: pathlib.Path) -> list[dict]:
    """
    Parse a translation markdown file into a list of verse dicts::

        [{"verse_id": "1-1", "text": "Reverently bowing..."}, ...]

    Lines starting with `![[...]]` (transclusion links) are skipped.
    Frontmatter is stripped. Heading lines (^N-0) are included but
    can be filtered downstream.
    """
    text  = strip_frontmatter(path.read_text(encoding="utf-8"))
    verses: list[dict] = []
    pending_lines: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("![["):
            continue
        m = _VERSE_MARKER.search(line)
        if m:
            verse_id = m.group(1)
            # last line of verse (may have text before the marker)
            last_line = line[: m.start()].strip()
            last_line = re.sub(r"^#+\s*", "", last_line).strip()
            if last_line:
                pending_lines.append(last_line)
            # join all accumulated lines as the full verse text
            verse_text = " ".join(pending_lines).strip()
            if verse_text:
                verses.append({"verse_id": verse_id, "text": verse_text})
            pending_lines = []
        else:
            # accumulate lines belonging to the current verse
            clean = re.sub(r"^#+\s*", "", line).strip()
            if clean:
                pending_lines.append(clean)
    return verses


def build_inverted_index(
    sources: list[pathlib.Path],
) -> dict[str, dict[str, list[dict]]]:
    """
    Pre-tokenize all verses once and return an inverted index::

        { stem: { word: [{"verse_id": ..., "text": ...}, ...] } }

    This lets write_keyword_verses_json do O(1) lookups per keyword
    instead of re-tokenizing every verse for every keyword.
    """
    index: dict[str, dict[str, list[dict]]] = {}
    for src in sources:
        stem   = src.stem
        inv: dict[str, list[dict]] = {}
        for verse in extract_verses(src):
            tokens = [w for w in tokenize(verse["text"]) if w not in STOPWORDS and len(w) > 2]
            word_counts: dict[str, int] = {}
            for word in tokens:
                word_counts[word] = word_counts.get(word, 0) + 1
            for word, cnt in word_counts.items():
                inv.setdefault(word, []).append(
                    {"verse_id": verse["verse_id"], "text": verse["text"], "count": cnt}
                )
        index[stem] = inv
    return index


def write_keyword_verses_json(
    comp: dict,
    sources: list[pathlib.Path],
    dest: pathlib.Path,
) -> None:
    """
    Write a JSON file mapping each English keyword to the verses where it appears.

    Output shape::

        {
          "word": {
            "score": <avg_tfidf>,
            "occurrences": [
              {"source": "en-Wallace", "verse_id": "1-3", "text": "..."},
              ...
            ]
          },
          ...
        }

    Words are sorted by average TF-IDF descending (same order as termbase).
    """
    stems = [src.stem for src in sources]

    # Build inverted index once: tokenize each verse a single time
    inv_index = build_inverted_index(sources)

    # Collect all English words sorted by avg TF-IDF
    all_words: set[str] = set()
    for d in comp.values():
        all_words.update(d["row_map"].keys())
    english_words = [w for w in all_words if is_english(w)]
    english_words.sort(
        key=lambda w: sum(comp[s]["row_map"].get(w, {}).get("score", 0.0) for s in stems) / len(stems),
        reverse=True,
    )

    result: dict = {}
    for rank, word in enumerate(english_words, 1):
        avg_score   = sum(comp[s]["row_map"].get(word, {}).get("score", 0.0) for s in stems) / len(stems)
        occurrences = [
            {"source": stem, "verse_id": v["verse_id"], "text": v["text"], "count": v.get("count", 1)}
            for stem in stems
            for v in inv_index[stem].get(word, [])
        ]
        if occurrences:
            total_count = sum(o.get("count", 1) for o in occurrences)
            result[word] = {
                "rank":        rank,
                "score":       round(avg_score, 4),
                "total_count": total_count,
                "occurrences": occurrences,
            }

    dest.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    total_occs = sum(len(v["occurrences"]) for v in result.values())
    print(f"Written  -> {dest}  ({len(result):,} keywords, {total_occs:,} verse occurrences)")
    return result


# ---------------------------------------------------------------------------
# Bottom-N report: most frequent keywords sorted by TF-IDF ascending
# ---------------------------------------------------------------------------

def write_bottom_json(
    keyword_data: dict,
    n: int,
    dest: pathlib.Path,
) -> None:
    """
    Write a JSON report of the N most frequent keywords sorted by TF-IDF ascending.

    Output shape::

        [
          {
            "bottom_rank": 1,
            "word": "said",
            "tfidf_rank": 2891,
            "score": 1337.83,
            "total_count": 12,
            "verses": 12
          },
          ...
        ]

    bottom_rank = position in this list (1 = most frequent among bottom scorers).
    tfidf_rank  = position in the full TF-IDF-descending list (1 = most distinctive).
    """
    pool = sorted(keyword_data.items(), key=lambda kv: -kv[1]["total_count"])[:n]
    pool.sort(key=lambda kv: kv[1]["score"])

    rows = []
    for bottom_rank, (word, d) in enumerate(pool, 1):
        rows.append({
            "bottom_rank": bottom_rank,
            "word":        word,
            "tfidf_rank":  d["rank"],
            "score":       d["score"],
            "total_count": d["total_count"],
            "verses":      len(d["occurrences"]),
        })

    dest.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Written  -> {dest}  ({len(rows):,} bottom keywords)")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Compute TF-IDF vocabulary analysis for one or more markdown "
            "translation files."
        ),
    )
    p.add_argument("--input", "-i", metavar="PATH", nargs="+", default=None,
                   help=f"Source markdown files. (default: {_DEFAULT_INPUT})")
    p.add_argument("--outdir", "-o", metavar="DIR", default=None,
                   help=f"Output directory. (default: {_DEFAULT_OUTDIR})")
    p.add_argument("--bottom", "-b", metavar="N", type=int, default=None,
                   help="Write bottom-N report: N most frequent keywords sorted by TF-IDF ascending.")
    return p.parse_args()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args   = _parse_args()
    outdir = pathlib.Path(args.outdir).resolve() if args.outdir else _DEFAULT_OUTDIR
    outdir.mkdir(parents=True, exist_ok=True)

    sources = (
        [pathlib.Path(p).resolve() for p in args.input]
        if args.input
        else [_DEFAULT_INPUT]
    )

    for src in sources:
        if not src.exists():
            raise FileNotFoundError(f"Translation not found:\n  {src}")

    comp       = build_comparison(sources)
    stems_slug = "_vs_".join(src.stem for src in sources) if len(sources) > 1 else sources[0].stem

    write_combined_json(comp, sources, outdir / (stems_slug + "_termbase.json"))

    kw_data = write_keyword_verses_json(comp, sources, outdir / (stems_slug + "_keyword_verses.json"))

    if args.bottom:
        write_bottom_json(kw_data, args.bottom, outdir / (stems_slug + f"_bottom_{args.bottom}.json"))

    write_verse_keywords_json(kw_data, outdir / (stems_slug + "_verse_keywords.json"))

    # ── Per-translation Markdown report ──────────────────────────────────────
    for src in sources:
        md_path = outdir / f"{src.stem}-tfidf.md"
        md_path.write_text(render_md(comp[src.stem]["rows"], src), encoding="utf-8")
        print(f"Written  -> {md_path}")

    # ── Cross-translation comparison Markdown report ─────────────────────────
    if len(sources) > 1:
        comparison_path = outdir / f"{stems_slug}-comparison.md"
        comparison_path.write_text(render_comparison_md(comp, sources), encoding="utf-8")
        print(f"Written  -> {comparison_path}")


# ---------------------------------------------------------------------------
# Verse-centric JSON: verse_id → {text, keywords}
# ---------------------------------------------------------------------------

def write_verse_keywords_json(
    keyword_data: dict,
    dest: pathlib.Path,
) -> None:
    """
    Invert keyword_data into a verse-centric structure.

    Output shape::

        {
          "6-22": {
            "text": "...",
            "keywords": [
              {"key": "beings", "rank": 3, "score": 97141.66, "count": 1},
              ...
            ]
          },
          ...
        }

    Keywords within each verse are sorted by TF-IDF rank ascending (most
    distinctive first).
    """
    verses: dict = {}

    for word, d in keyword_data.items():
        for occ in d["occurrences"]:
            vid = occ["verse_id"]
            if vid not in verses:
                verses[vid] = {"text": occ["text"], "keywords": []}
            verses[vid]["keywords"].append({
                "key":         word,
                "rank":        d["rank"],
                "score":       d["score"],
                "count":       occ.get("count", 1),
            })

    # sort keywords within each verse by rank ascending (most distinctive first)
    for v in verses.values():
        v["keywords"].sort(key=lambda k: k["rank"])

    # sort verses by verse_id (natural sort on chapter-verse)
    def verse_sort_key(vid: str):
        parts = re.split(r"[-]", vid)
        try:
            return [int(p) for p in parts]
        except ValueError:
            return [0]

    ordered = dict(sorted(verses.items(), key=lambda kv: verse_sort_key(kv[0])))

    dest.write_text(json.dumps(ordered, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Written  -> {dest}  ({len(ordered):,} verses)")


if __name__ == "__main__":
    main()
