from __future__ import annotations
import json
import os
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from languages import (
    LANGUAGE_VALUES as _LV,
    LANGUAGE_NAME_MAP as _LNM,
    LANGUAGE_CODE_TO_NAME as _LC2N,
)

LICENSE_VALUES = frozenset({
    "cc0", "public", "cc-by", "cc-by-sa", "cc-by-nd",
    "cc-by-nc", "cc-by-nc-sa", "cc-by-nc-nd", "copyrighted", "unknown",
})
ROLE_VALUES = frozenset({"translator", "reviser", "author", "scholar"})

# Runtime copies — updated by load_languages() (all mutable so imports stay live)
LANGUAGE_VALUES: set = set(_LV)
LANGUAGE_NAME_MAP: dict = dict(_LNM)
LANGUAGE_CODE_TO_NAME: dict = dict(_LC2N)
LANG_TAG_MAP: dict = {c: c for c in _LV}

ALLOWED_KEYS = frozenset({
    "bdrc", "wiki", "date", "title", "alt_titles", "language",
    "commentary_of", "translation_of", "category_id", "license",
    "contributions", "tag_ids",
})
VAULT_ONLY_KEYS = frozenset({
    "file_type", "lang_tag", "language_tag", "source_description",
    "verse_id_format", "root_text", "covers_verses", "bdrc_work_id",
    "cbeta_id", "gretil_url", "dsbc_url", "suttacentral_id", "acip_id",
    "registered_id", "status",
})
MAPPED_DOC_KEYS = frozenset({
    "title in English", "author in English",
    "title_in_english", "author_in_english",
})
SCHEMA_FIELDS = (
    "bdrc", "wiki", "date", "title", "alt_titles", "language",
    "commentary_of", "translation_of", "category_id", "license",
    "contributions", "tag_ids",
)

# FORK(21-taras-rails, 2026-09-17): the OpenPecha host these pointed at answers
# 404 for /v2/languages, so load_languages() silently fell back to the cached
# languages.py (frozen 2026-08-05, no `ne`). This vault uploads to the
# WeBuddhist library, whose language list is public and is the one that
# matters (it carries `ne`, `mr`, …). Override with VAULT_API_BASE if needed.
_API_BASE = os.environ.get("VAULT_API_BASE", "https://library.webuddhist.com").rstrip("/")
PERSONS_API = f"{_API_BASE}/v2/persons"
LANGUAGES_API = f"{_API_BASE}/v2/languages"
BDRC_SEARCH = "https://autocomplete.bdrc.io/msearch"

BDRC_LABEL_LANGS = {
    "prefLabel_bo_x_ewts": "bo",
    "prefLabel_iast": "sa",
    "prefLabel_pi": "pi",
    "prefLabel_hani": "lzh",
    "prefLabel_zh": "lzh",
    "prefLabel_en": "en",
    "prefLabel_fr": "fr",
    "prefLabel_ja": "ja",
    "prefLabel_mn": "mn",
    "prefLabel_mn_x_mong": "mn",
    "prefLabel_ru": "ru",
}
BDRC_TTL_LANG_MAP = {
    "bo": "bo", "bo-x-ewts": "bo", "bo-x-dbu-can": "bo",
    "sa": "sa", "sa-x-iast": "sa", "sa-x-ewts": "sa",
    "pi": "pi", "pi-x-iast": "pi",
    "zh": "lzh", "zh-hant": "lzh", "lzh": "lzh",
    "en": "en", "fr": "fr", "ja": "ja", "mn": "mn",
    "mn-x-mong": "mn", "ru": "ru",
}
LANG_TO_BCP47 = {
    "bo":  ["bo", "bo-x-ewts", "bo-x-dbu-can"],
    "sa":  ["sa-x-iast", "sa"],
    "pi":  ["pi-x-iast", "pi"],
    "lzh": ["zh", "zh-hant", "lzh"],
    "en":  ["en"],
    "fr":  ["fr"],
    "ja":  ["ja"],
    "mn":  ["mn", "mn-x-mong"],
    "ru":  ["ru"],
}


def _call_api(url, timeout=10):
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception:
        return None


def _write_languages_file(name_map: dict, code_map: dict):
    """Persist fetched language data to languages.py."""
    lang_file = Path(__file__).parent / "languages.py"
    timestamp = datetime.now(timezone.utc).isoformat()
    lines = [
        "# AUTO-GENERATED by load_languages() — do not edit manually.",
        f"# Last updated: {timestamp}",
        f"LANGUAGE_VALUES = frozenset({{{', '.join(repr(c) for c in sorted(code_map))}}})",
        "LANGUAGE_NAME_MAP = {",
    ]
    for k, v in sorted(name_map.items()):
        lines.append(f"    {k!r}: {v!r},")
    lines.append("}")
    lines.append("LANGUAGE_CODE_TO_NAME = {")
    for k, v in sorted(code_map.items()):
        lines.append(f"    {k!r}: {v!r},")
    lines.append("}")
    content = "\n".join(lines) + "\n"
    lang_file.write_bytes(content.encode("utf-8"))


def load_languages():
    """Fetch language list from API, update runtime globals, persist to languages.py."""
    try:
        data = _call_api(LANGUAGES_API)
        if not isinstance(data, list) or not data:
            raise ValueError("unexpected response")
        name_map, code_map = {}, {}
        for entry in data:
            code = entry.get("code", "").strip()
            name = entry.get("name", "").strip()
            if code and name:
                name_map[name.lower()] = code
                code_map[code] = name
        if not code_map:
            raise ValueError("no valid entries in response")
        # Mutate in place so all importers see the update
        LANGUAGE_VALUES.clear()
        LANGUAGE_VALUES.update(code_map)
        LANGUAGE_NAME_MAP.clear()
        LANGUAGE_NAME_MAP.update(name_map)
        LANGUAGE_CODE_TO_NAME.clear()
        LANGUAGE_CODE_TO_NAME.update(code_map)
        LANG_TAG_MAP.clear()
        LANG_TAG_MAP.update({c: c for c in code_map})
        _write_languages_file(name_map, code_map)
    except Exception:
        # API unreachable — runtime values come from languages.py import
        pass
