# AUTO-GENERATED by load_languages() — do not edit manually.
# Last updated: 2026-09-17T10:48:08.760269+00:00
LANGUAGE_VALUES = frozenset({'bo', 'en', 'fr', 'hi', 'ja', 'lzh', 'mn', 'mr', 'ne', 'pi', 'ru', 'sa', 'vi', 'zh'})
LANGUAGE_NAME_MAP = {
    'chinese': 'zh',
    'classical chinese': 'lzh',
    'english': 'en',
    'french': 'fr',
    'hindi': 'hi',
    'japanese': 'ja',
    'marathi': 'mr',
    'mongolian': 'mn',
    'nepali': 'ne',
    'pali': 'pi',
    'russian': 'ru',
    'sanskrit': 'sa',
    'tibetan': 'bo',
    'vietnamese': 'vi',
}
LANGUAGE_CODE_TO_NAME = {
    'bo': 'tibetan',
    'en': 'english',
    'fr': 'french',
    'hi': 'hindi',
    'ja': 'japanese',
    'lzh': 'classical chinese',
    'mn': 'mongolian',
    'mr': 'Marathi',
    'ne': 'nepali',
    'pi': 'pali',
    'ru': 'russian',
    'sa': 'sanskrit',
    'vi': 'vietnamese',
    'zh': 'chinese',
}
